version: '3.9'
services:
    rasa:
      container_name: "rasa_server"
      user: root
      build: 
        context:  .
      volumes:
      - "./:/app"
      ports: 
        - "5005:5005"
        
    action_server:
      container_name: "action_server"
      build: 
        context: .
        dockerfile: action.Dockerfile
      volumes:
        - ./actions:/app/actions
        - ./data:/app/data
      ports:
        - 5055:5055
    
