version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_rasa
    command: >
      sh -c "rasa run"
    volumes:
      - .:/code

    restart: on-failure
    ports:
      - "5005:5005"
    